permissions:
  broadcast-msg: messagemanager.broadcast
  staff-chat: messagemanager.staffchat
  msg: messagemanager.msg

error-msgs:
  no-permission: "&c&lERROR &7» &fYou do not have the correct permission for this command!"
  not-enough-args: "&c&lERROR &7» &fYou haven't put enough arguments for this command."

player-logging:
  # Join/Leave Placeholders
  # %player_name% - player's username
  # %player_displayname% - player's display name
  # Join Messages
  join-enabled: true
  join-msg: "&a&lJOIN &7» &f%player_name% &ahas joined the game!"
  # Leave Messages
  leave-enabled: true
  leave-msg: "&c&lLEAVE &7» &f%player_name% &chas left the game!"
  # First Time Joining Messages
  first-time-enabled: true
  first-time-msg: "&3&lWELCOME &7» &f%player_name% &ahas joined the game for the first time!"

staff-chat:
  # Staff-Chat Placeholders #
  # %player_name% - player's username #
  # %player_displayname% - player's display name #
  # %message% - message sent to the staff-chat #
  enabled: true
  quick-msg: "@" # Starting a message with this will auto go to staff-chat #
  msg-format: "&9&lSTAFFCHAT &7» &f%player_name% &c: &c%message%"
  # Staff Chat Messages being seen or not
  toggled-view-on: "&9&lSTAFFCHAT &7» &cYou will see Staff-Chat Messages"
  toggled-view-off: "&9&lSTAFFCHAT &7» &cYou will no longer see Staff-Chat Messages"
  # Staff Chat Messages sent by default to everyone, or to public chat
  toggled-on: "&9&lSTAFFCHAT &7» &cMessages by default will go to &astaff chat"
  toggled-off: "&9&lSTAFFCHAT &7» &cMessages by default will go to &epublic chat"

broadcast:
  # Broadcast Placeholders
  # %player_name% - player's username
  # %player_displayname% - player's display name
  # %message% - message sent to be broadcasted
  enabled: true
  msg: "&4&lBROADCAST &8[&c%player_name%&8] &7» &f%message%"