name: MessageManager
version: '${project.version}'
main: me.tailer.MessageManager
api-version: 1.20
authors: [ tailerr ]
description: Manage all messages on your server!

commands:
  sc:
    usage: /<command>
    aliases:
      - staffchat
  scview:
    usage: /<command>
    aliases:
      - staffchatview
  sctoggle:
    usage: /<command>
    aliases:
      - staffchattoggle
  broadcast:
    usage: /<command>
    aliases:
      - bc
  msg:
    usage: /<command>
    aliases:
      - message
      - m
      - whisper
  reply:
    usage: /<command>
    aliases:
      - r
      - respond
